### ISSUE TITLE
Env variable names in GatsbyJS

### ISSUE THREAD

**Issue by 105ron** [imorente/gatsby-netlify-form-example#11]
From the [GatsbyJS docs](https://www.gatsbyjs.org/docs/environment-variables/) it says...

> In addition to .env.* files, any variable in the environment prefixed with GATSBY_ will be made available in browser JavaScript.

Should the `SITE_RECAPTCHA_KEY` variable be renamed to `GATSBY_SITE_RECAPTCHA_KEY` within the `.env.developement` and line 5 of `recaptcha.js` ? I was having difficulty getting the key to load in environment and production until I found this in the documents and changed it with your example. Thank you for providing this repo to assist with netlify forms.

**Comment by imorente** [comment]
When I tried out this example, environment variables defined in .env.* files didn't need to be prefixed with `GATSBY_`. Variables prefixed with `GATSBY_` were made available _in addition_ to those defined in .env.* files. Has this changed recently?

For Netlify to run server-side validation on the recaptcha, the environment variable needs to be called `SITE_RECAPTCHA_KEY`. If you rename it to `GATSBY_SITE_RECAPTCHA_KEY `, make sure to add a `SITE_RECAPTCHA_KEY` environment variable as well.

**Comment by 105ron** [comment]
Hi @imorente ,
I was having trouble getting the recaptcha to display on local and the netlify server until I changed the environment variables. It seemed to display correctly when I prefixed with `GATSBY_` but the messages reach the netlify server and fail to display (I think it's failing the back end validation but I do still have the `SITE_RECAPTCHA_KEY` on netlify).

I just thought I would mention it here in case someone else is having similar issues.

**Comment by imorente** [comment]
and you had `env.development` and `env.production` files with the `SITE_RECAPTCHA_KEY` variable?

**Comment by 105ron** [comment]
I don't have `env.production` but all the `env` files are ignored by git so netlify doesn't have access to them via the repository when building the site. I thought adding them on the netlify site in build environment variables would be all that is required? And the build command on netlify settings is `echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> env.production && gatsby build`

**Comment by imorente** [comment]
yeah, that `echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> env.production && gatsby build` is the trick I used to generate an `env.production` without having to commit it to the repository. 

Not sure how to replicate the issue you're having. You mentioned you had the same problem in development. Do you have an `env.development` locally?

**Comment by 105ron** [comment]
I do but I can't really test it on development because I need the Netlify back end to process the data. A message got through yesterday and despite not changing anything the messages are being blocked again. There was some delay in it appearing - I don't think I'll be able to fix the issue.

**Comment by nimaiwalsh** [comment]
I am also getting an error in console when trying to view the form on Netlify. 
`react-dom.production.min.js:212 Uncaught Error: Missing required parameters: sitekey`

It works locally when using my .env.development file.

I have added echo `SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> env.production && gatsby build` to Netfly as the build command.

Both site variables have been added to netlify. SITE_RECAPTCHA_KEY set as the KEY and the key code set as VALUE.

Any ideas?

**UPDATE**
My solutions to the problem above.

1. I replaced my variable names on Netlify with: `GATSBY_SITE_RECAPTCHA_KEY` and `GATSBY_SITE_RECAPTCHA_SECRET`
2. Updated my variable in my form.js file with` const RECAPTCHA_KEY = process.env.GATSBY_SITE_RECAPTCHA_KEY;`
3. Updated Build command on Netlify with `echo GATSBY_SITE_RECAPTCHA_KEY=$GATSBY_SITE_RECAPTCHA_KEY >> env.production && gatsby build`

This solved my issue when viewing the form on Netlify.

My next issue was that Netlfiy was not receiving the form data after using ReCaptcha. It registered a response and incremented the submission count, but did list the submission itself.

I had to include  `data-netlify-honeypot="bot-field"` as a form parameter which solved the issue.

**Comment by nimaiwalsh** [comment]
I ended up getting it to work.

1. I replaced my variable names on Netlify with: GATSBY_SITE_RECAPTCHA_KEY and GATSBY_SITE_RECAPTCHA_SECRET
2. Updated my variable in my form.js file with` const RECAPTCHA_KEY = process.env.GATSBY_SITE_RECAPTCHA_KEY;`
3. Updated Build command on Netlify with `echo GATSBY_SITE_RECAPTCHA_KEY=$GATSBY_SITE_RECAPTCHA_KEY >> env.production && gatsby build`

This solved my issue when viewing the form on Netlify.

My next issue was that Netlfiy was not receiving the form data after using ReCaptcha. It registered a response and incremented the submission count, but did not list of content.

I had to include  `data-netlify-honeypot="bot-field"` as a form parameter which solved the issue. Now working correctly :)

**Comment by jmgq** [comment]
Just in case anyone else was having the `Error: Missing required parameters: sitekey` message in production, I solved it by ensuring that the env file starts with a dot (`.env.production` rather than `env.production`):

```
echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> .env.production && gatsby build
```

In the Readme, it does not start with a dot. I wonder if this is something that changed from GatsbyJS v1 to v2 (I never used v1).

**Comment by imorente** [comment]
Thanks for catching that typo! Fixed the README 🤦‍♀️
