### ISSUE TITLE
Recaptcha submissions not working

### ISSUE THREAD

**Issue by liywjl** [imorente/gatsby-netlify-form-example#12]
I am unable to get any forms to appear on the backend when using recaptcha.

Could you update your examples or give clarification on the issue?

**Comment by SKempin** [comment]
@liywjl try adding `data-netlify-honeypot="bot-field"` as a form parameter, as detailed in https://github.com/imorente/gatsby-netlify-form-example/issues/11#issuecomment-412477395

Also ensure you have environment variables set up, as detailed in that thread.

**Comment by chiester** [comment]
The readme indicates that the file for environment variables is called 'env.production', but it needs to have a preceding period so it is '.env.production'.  That tripped me up but when I changed it, the reCaptcha started working.
